# -*- coding: utf-8 -*-
"""Network Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWSXRzCcvKdopaA1iEMhhjeiEcUyI-OV

##Network Analysis on Bitcoin OTC trust weighted signed network dataset

About the dataset: This is who-trusts-whom network of people who trade using Bitcoin on a platform called Bitcoin OTC. Since Bitcoin users are anonymous, there is a need to maintain a record of users' reputation to prevent transactions with fraudulent and risky users. Members of Bitcoin OTC rate other members in a scale of -10 (total distrust) to +10 (total trust) in steps of 1. This is the first explicit weighted signed directed network available for research.

##columns

source (Node): The user or entity giving the rating (trustor)

target (Node): The user or entity receiving the rating (trustee)

rating (Edge weight):The trust score or sentiment given by the source to the target (positive = trust, negative = distrust)

timestamp :The date and time when the rating was given
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import networkx as nx

df = pd.read_csv('/content/soc-sign-bitcoinotc.csv', names=["source", "target", "rating", "timestamp"])
df.head()

df.tail()

#changing timestamp to datetime data
df['timestamp'] = pd.to_datetime(df['timestamp'], unit='s')

df.head()

df.tail()

df.info()

#creating a network graph
G = nx.DiGraph()
for _, row in df.iterrows():
    G.add_edge(row["source"], row["target"], weight=row["rating"])

print("\nGraph Created:")
# Basic network properties
num_nodes = G.number_of_nodes()
num_edges = G.number_of_edges()
density = nx.density(G)
avg_clustering = nx.average_clustering(G.to_undirected(), weight='rating')

print(f"Nodes: {num_nodes}")
print(f"Edges: {num_edges}")
print(f"Density: {density}")
print(f"Average Clustering Coefficient: {avg_clustering}")

# Select the top 200 most connected users based on degree
top_nodes = sorted(G.degree(), key=lambda x: x[1], reverse=True)[:200]  # Change to 100 if needed
selected_users = [node for node, _ in top_nodes]
subG = G.subgraph(selected_users)

# Generate a force-directed layout for better spacing
plt.figure(figsize=(12, 8))
pos = nx.spring_layout(subG, seed=42, k=0.7)  # Higher k spreads nodes out more

# Draw nodes with a reasonable size
nx.draw_networkx_nodes(subG, pos, node_size=50, node_color='lightblue', edgecolors='black', alpha=0.8)

# Draw edges with reduced opacity to prevent clutter
nx.draw_networkx_edges(subG, pos, alpha=0.3, width=0.7)

# Display labels for the most connected users
nx.draw_networkx_labels(subG, pos, font_size=8, font_color='darkblue')

plt.title("Bitcoin Trust Network - Top 200 Users")
plt.show()

#Who are the most influential users in the trust network?
# Compute degree centrality
degree_centrality = nx.degree_centrality(G)

# Get top 20 nodes by degree centrality
top_degree = sorted(degree_centrality.items(), key=lambda x: x[1], reverse=True)[:20]
top_users = {user for user, _ in top_degree}

# Print top 20 nodes
print("\nTop 20 Nodes by Degree Centrality:")
for user, score in top_degree:
    print(f"User {user}: {score}")

# Create a subgraph with only the top 20 users
subG = G.subgraph(top_users)

# Draw the network graph
plt.figure(figsize=(10, 8))
pos = nx.spring_layout(subG, seed=42)  # Layout for visualization
node_size = [degree_centrality[node] * 5000 for node in subG.nodes()]  # Scale node size by degree centrality

nx.draw(subG, pos, with_labels=True, node_color='lightcoral', node_size=node_size, edge_color='gray', font_size=8)
plt.title("Top 20 Nodes by Degree Centrality in the Bitcoin Trust Network")
plt.show()

# Identifying Influential Users (PageRank)
# Compute PageRank with weight
pagerank = nx.pagerank(G, weight='rating')

# Get top 20 influential users
top_influential = sorted(pagerank.items(), key=lambda x: x[1], reverse=True)[:20]
top_users = {user for user, _ in top_influential}

# Print top 20 influential users
print("\nTop 20 Influential Users (PageRank):")
for user, score in top_influential:
    print(f"User {user}: {score}")

# Create a subgraph with only the top influential users and their connections
subG = G.subgraph(top_users)

# Draw the network graph
plt.figure(figsize=(10, 8))
pos = nx.spring_layout(subG, seed=42)  # Positioning for better visualization
node_size = [pagerank[node] * 5000 for node in subG.nodes()]  # Scale node size by PageRank score

nx.draw(subG, pos, with_labels=True, node_color='orange', node_size=node_size, edge_color='gray', font_size=8)
plt.title("Top 20 Influential Users in the Bitcoin Trust Network (PageRank)")
plt.show()

# Who are the key intermediaries bridging trust between groups?
betweenness = nx.betweenness_centrality(G, weight='rating')
top_intermediaries = sorted(betweenness.items(), key=lambda x: x[1], reverse=True)[:20]
print("\nTop 20 Users Acting as Intermediaries:")
for user, score in top_intermediaries:
    print(f"User {user}: {score}")



# Get top 20 intermediaries
top_intermediaries = sorted(betweenness.items(), key=lambda x: x[1], reverse=True)[:20]
top_users = {user for user, _ in top_intermediaries}

# Create a subgraph with only the top intermediaries and their connections
subG = G.subgraph(top_users)

# Draw the network graph
plt.figure(figsize=(10, 8))
pos = nx.spring_layout(subG, seed=42)  # Positioning for better visualization
node_size = [betweenness[node] * 2000 for node in subG.nodes()]  # Scale node size by centrality

nx.draw(subG, pos, with_labels=True, node_color='skyblue', node_size=node_size, edge_color='gray', font_size=8)
plt.title("Top 20 Intermediaries in the Bitcoin Trust Network")
plt.show()

# Are there users who receive high trust but give low trust?
in_degree = dict(G.in_degree(weight='rating'))
out_degree = dict(G.out_degree(weight='rating'))
disparity_users = [(u, in_degree[u], out_degree.get(u, 0)) for u in in_degree if in_degree[u] > 2 * out_degree.get(u, 0)]
top_disparity = sorted(disparity_users, key=lambda x: x[1], reverse=True)[:10]
print("\nTop 10 Users Receiving High Trust but Giving Low Trust:")
for user, received, given in top_disparity:
    print(f"User {user}: Received {received}, Given {given}")

# Visualization for High Trust but Low Trust-Giving Users
if top_disparity:
    disparity_df = pd.DataFrame(top_disparity, columns=["User", "Received Trust", "Given Trust"])
    plt.figure(figsize=(10, 5))
    sns.barplot(x="User", y="Received Trust", data=disparity_df, color='blue', label='Received Trust')
    sns.barplot(x="User", y="Given Trust", data=disparity_df, color='red', label='Given Trust')
    plt.xlabel("User ID")
    plt.ylabel("Trust Score")
    plt.title("Users Receiving High Trust but Giving Low Trust")
    plt.legend()
    plt.show()

#How is trust distributed among users in the Bitcoin OTC network?
from community import community_louvain
df_positive = df[df['rating'] > 0]  # Use only positive trust for community detection

# Create undirected graph (communities) with summed positive ratings
G_undirected = nx.from_pandas_edgelist(
    df_positive,
    'source',
    'target',
    edge_attr='rating',
    create_using=nx.Graph()
)

# Simplify edge weights by summing multiple ratings between the same users
G_undirected = nx.Graph()
for _, row in df_positive.iterrows():
    if G_undirected.has_edge(row['source'], row['target']):
        G_undirected[row['source']][row['target']]['rating'] += row['rating']
    else:
        G_undirected.add_edge(row['source'], row['target'], rating=row['rating'])

# --------------------------------------------
# 9. Detect Communities (Fixed)
# --------------------------------------------
partition = community_louvain.best_partition(G_undirected, resolution=0.8)
community_counts = pd.Series(partition).value_counts().head(5)
print("\nTop 5 Largest Communities:")
print(community_counts)

plt.figure(figsize=(14, 8))
pos = nx.spring_layout(G_undirected, seed=42)
node_colors = [partition[node] for node in G_undirected.nodes()]
nx.draw_networkx_nodes(G_undirected, pos, node_size=50, node_color=node_colors, cmap=plt.cm.tab20, alpha=0.8)
nx.draw_networkx_edges(G_undirected, pos, alpha=0.1)

# How does trust change over time in the network?
# Trust Evolution Over Time
df.set_index('timestamp', inplace=True)
trust_over_time = df['rating'].resample('M').mean()
plt.figure(figsize=(10, 5))
trust_over_time.plot(color='purple')
plt.xlabel("Time")
plt.ylabel("Average Trust Score")
plt.title("Trust Evolution Over Time")
plt.show()

#Are there significant events that correspond to major shifts in trust?
events = {
    "2013-02": "Mt. Gox Hack",
    "2014-02": "Mt. Gox Collapse",
    "2015-07": "Bitcoin XT Fork"
}

plt.figure(figsize=(10, 5))
trust_over_time.plot(color='purple')
plt.xlabel("Time")
plt.ylabel("Average Trust Score")
plt.title("Trust Evolution Over Time")

# Mark events
for date, event in events.items():
    plt.axvline(pd.to_datetime(date), color='red', linestyle="--", alpha=0.7)
    plt.text(pd.to_datetime(date), trust_over_time.max(), event, rotation=45, color='red')

plt.show()

#How do users regain trust after a decline?
initial_trust = df[df.index < "2013-01-01"].groupby("source")["rating"].mean()
final_trust = df[df.index > "2015-01-01"].groupby("source")["rating"].mean()
trust_recovery = pd.DataFrame({"Initial": initial_trust, "Final": final_trust}).dropna()
trust_recovery["Change"] = trust_recovery["Final"] - trust_recovery["Initial"]

print("\nTop 10 Users Who Gained the Most Trust Over Time:")
print(trust_recovery.sort_values("Change", ascending=False).head(10))

#Does More Trust Ratings Mean Higher Trust?

# Set timestamp as index
df.set_index('timestamp', inplace=True)

# Calculate trust rating volume (count of ratings per month)
trust_volume = df.resample('M').size()

# Calculate average trust score per month
trust_over_time = df['rating'].resample('M').mean()

# Create a dual-axis plot
fig, ax1 = plt.subplots(figsize=(12, 6))

# Plot trust rating volume
color = 'purple'
ax1.set_xlabel("Time")
ax1.set_ylabel("Number of Trust Ratings", color=color)
ax1.plot(trust_volume.index, trust_volume.values, marker='o', color=color, label="Trust Ratings")
ax1.tick_params(axis='y', labelcolor=color)

# Create second y-axis
ax2 = ax1.twinx()
color = 'blue'
ax2.set_ylabel("Average Trust Score", color=color)
ax2.plot(trust_over_time.index, trust_over_time.values, marker='s', linestyle='--', color=color, label="Avg Trust Score")
ax2.tick_params(axis='y', labelcolor=color)

# Title and legend
plt.title("Trust Rating Volume & Trust Evolution Over Time")
fig.legend(loc="upper left", bbox_to_anchor=(0.1,0.9))
plt.show()

# Resample to monthly data
trust_volume = df.resample('M').size()
trust_over_time = df['rating'].resample('M').mean()

# Compute correlation
correlation_pearson = trust_volume.corr(trust_over_time, method='pearson')
correlation_spearman = trust_volume.corr(trust_over_time, method='spearman')

# Plot correlation heatmap
corr_df = pd.DataFrame({'Trust Volume': trust_volume, 'Trust Score': trust_over_time})
corr_matrix = corr_df.corr()

plt.figure(figsize=(6, 4))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Between Trust Volume and Trust Score")
plt.show()

print(f"Pearson Correlation: {correlation_pearson:.2f}")
print(f"Spearman Correlation: {correlation_spearman:.2f}")